### ISSUE TITLE
[F]: Please, install ADB!

### ISSUE THREAD

**Issue by deyvs02** [R0rt1z2/AutomatedRoot#10]
Even though I installed the requirements it still asks to install

**Comment by R0rt1z2** [comment]
> Even though I installed the requirements it still asks to install

Are you using Windows or Linux? Can you manually try to start the ADB server before using the tool (`adb start-server`)?

**Comment by deyvs02** [comment]
> > Even though I installed the requirements it still asks to install
> 
> Are you using Windows or Linux? Can you manually try to start the ADB server before using the tool (`adb start-server`)?

ok i'm using windows

I will try to start and let you know

**Comment by deyvs02** [comment]
> adb start-server

     _____     _                 _         _ _____         _
    |  _  |_ _| |_ ___ _____ ___| |_ ___ _| | __  |___ ___| |_
    |     | | |  _| . |     | .'|  _| -_| . |    -| . | . |  _|
    |__|__|___|_| |___|_|_|_|__,|_| |___|___|__|__|___|___|_|   v7.0

    -> 1. Root the device (system-mode).
    -> 2. Root the device (bootless-mode).
    -> 3. Unroot the device.
    -> 4. Exit the tool.

[I]: Please select >>


WORK
THANKS
