### ISSUE TITLE
[F]: Please, install ADB!

### ISSUE THREAD

**Issue by thesmbbross** [R0rt1z2/AutomatedRoot#11]
when ever i try to run the program it gives me this error ([F]: Please, install ADB!)
even when i have it installed what do i do?
(i tried the method in the closed issue with the same error and it didnt work/ i dont know how to start the server manually

**Comment by R0rt1z2** [comment]
> when ever i try to run the program it gives me this error ([F]: Please, install ADB!) even when i have it installed what do i do? (i tried the method in the closed issue with the same error and it didnt work/ i dont know how to start the server manually

Are you using Windows or Linux?

**Comment by thesmbbross** [comment]
> > when ever i try to run the program it gives me this error ([F]: Please, install ADB!) even when i have it installed what do i do? (i tried the method in the closed issue with the same error and it didnt work/ i dont know how to start the server manually
> 
> Are you using Windows or Linux?

windows 10

**Comment by R0rt1z2** [comment]
> > > when ever i try to run the program it gives me this error ([F]: Please, install ADB!) even when i have it installed what do i do? (i tried the method in the closed issue with the same error and it didnt work/ i dont know how to start the server manually
> > 
> > 
> > Are you using Windows or Linux?
> 
> windows 10

Whenever you try to start the server manually (`adb start-server`), what does the command prompt show?

**Comment by thesmbbross** [comment]
![image](https://user-images.githubusercontent.com/67525177/154866608-4ad8c6c3-ee8e-40da-a93f-92c4fd7d2662.png)


> > > > when ever i try to run the program it gives me this error ([F]: Please, install ADB!) even when i have it installed what do i do? (i tried the method in the closed issue with the same error and it didnt work/ i dont know how to start the server manually
> > > 
> > > 
> > > Are you using Windows or Linux?
> > 
> > 
> > windows 10
> 
> Whenever you try to start the server manually (`adb start-server`), what does the command prompt show?

**Comment by thesmbbross** [comment]
sometimes it shows this
![image](https://user-images.githubusercontent.com/67525177/154866650-5b68640f-682a-4640-b064-2be7eb401020.png)

**Comment by thesmbbross** [comment]
but usualy it still shows this when
![image](https://user-images.githubusercontent.com/67525177/154866724-7877e3f4-80cc-4618-935f-19c0acf5dda3.png)
 i run the start command 
 C:\Users\thesm\Downloads\AutomatedRoot-v7.0\mtk-su.py

**Comment by R0rt1z2** [comment]
> sometimes it shows this ![image](https://user-images.githubusercontent.com/67525177/154866650-5b68640f-682a-4640-b064-2be7eb401020.png)

Can you change [this line](https://github.com/R0rt1z2/AutomatedRoot/blob/main/mtk-su.py#L18) to `logger.die(f"Please, install ADB ({e})!", 3)`, run the script again and show me the output?

**Comment by thesmbbross** [comment]
> 

how do i do that?

**Comment by R0rt1z2** [comment]
Try with [this version](https://github.com/R0rt1z2/AutomatedRoot/files/8105050/automated_root.zip) and show me the output of the script.

**Comment by thesmbbross** [comment]
how do i try it with that ?

**Comment by thesmbbross** [comment]
![image](https://user-images.githubusercontent.com/67525177/154866988-f361cbfe-4f4f-47ee-8d7b-69b1476b5c1c.png)

**Comment by thesmbbross** [comment]
oooh i see now ill try it now

> Try with [this version](https://github.com/R0rt1z2/AutomatedRoot/files/8105050/automated_root.zip) and show me the output of the script.

**Comment by thesmbbross** [comment]
![image](https://user-images.githubusercontent.com/67525177/154867407-81b4b87e-b9a1-4ca9-a180-4b79ef1823fa.png)


> Try with [this version](https://github.com/R0rt1z2/AutomatedRoot/files/8105050/automated_root.zip) and show me the output of the script.

this is the output

**Comment by thesmbbross** [comment]
?

**Comment by thesmbbross** [comment]
are you there?

**Comment by thesmbbross** [comment]
> Try with [this version](https://github.com/R0rt1z2/AutomatedRoot/files/8105050/automated_root.zip) and show me the output of the script.



> ![image](https://user-images.githubusercontent.com/67525177/154867407-81b4b87e-b9a1-4ca9-a180-4b79ef1823fa.png)
> 
> > Try with [this version](https://github.com/R0rt1z2/AutomatedRoot/files/8105050/automated_root.zip) and show me the output of the script.
> 
> this is the output

i did it whats going on with it?

**Comment by thesmbbross** [comment]
?

**Comment by R0rt1z2** [comment]
Please don't spam with useless comments.

The error message `The system cannot find the file specified` means that the tool was unable to start the server because the `adb` binary is not present in the %PATH%.

As the README says, add the binary to the %PATH% or copy the binary to some folder which is already in the path (for instance, `C:\Windows\`.

**Comment by thesmbbross** [comment]
what binary do i move there?

**Comment by thesmbbross** [comment]
okay so ive done everything and im at the final steps but when i press run scripts now on my device it says that it "failed critical init step 4: this firmware cannot be supported" what do i do now?

**Comment by R0rt1z2** [comment]
> okay so ive done everything and im at the final steps but when i press run scripts now on my device it says that it "failed critical init step 4: this firmware cannot be supported" what do i do now?

Your device is just not vulnerable to mtk-su.

**Comment by thesmbbross** [comment]
is there any other way to root this damn tablet?
its specifically a fire hd 8 (8th gen 2018)

**Comment by R0rt1z2** [comment]
> is there any other way to root this damn tablet? its specifically a fire hd 8 (8th gen 2018)

If your device was not updated to the latest version, you can try using [amonet](https://forum.xda-developers.com/t/unlock-root-twrp-unbrick-fire-hd-8-2018-karnak-amonet-3.3963496/).

**Comment by thesmbbross** [comment]
what firmware is the maximum that will work with this method (amonet)

**Comment by R0rt1z2** [comment]
> what firmware is the maximum that will work with this method (amonet)

No idea, check the XDA thread for more information.
