### ISSUE TITLE
Failed to work on Npad S (shown as MT8183 in Android Device Info)

### ISSUE THREAD

**Issue by kostapr** [R0rt1z2/AutomatedRoot#13]
Linux Ubuntu 22.04.3
================
The script shows the device as MT8788, the Android Device Info reports it as MT8183
```
     _____     _                 _         _ _____         _   
    |  _  |_ _| |_ ___ _____ ___| |_ ___ _| | __  |___ ___| |_ 
    |     | | |  _| . |     | .'|  _| -_| . |    -| . | . |  _|
    |__|__|___|_| |___|_|_|_|__,|_| |___|___|__|__|___|___|_|   

[I]: Found device = XXXXXXXXXXXXX
[I]: Handshake

* * * If your device is not authorized, authorize it now * * *

[I]: Dump device info
[F]: Invalid platform: mt8788

$ cat devinfo.txt 
Model -> NpadS
Android Version -> 12
Product Manufracturer -> N-one
Security Patch -> 2023-05-05
```

**Comment by biemster** [comment]
Got an Npad S here too, but mt8183 is also not supported by this code right?
So it wouldn't work even if it detected the proper platform?

**Comment by biemster** [comment]
Although it might work actually, since mt8183 is very similar to the supported mt6771 and the thread on XDA for mtk-su actually mentions the mt8183. I'm going to try this now.

**Comment by biemster** [comment]
`getprop ro.hardware` indeed reports mt8788, so it's a bug in the npad and not this application.
`cat /proc/cpuinfo` correctly lists MT8183

**Comment by biemster** [comment]
So yeah, doesn't work because the firmware on the Npad S is too new and is patched against this.

**Comment by GreatWizard** [comment]
Same issue about the TCL NxtPaper 11

> Model -> 9466X
> Android Version -> 13
> Product Manufracturer -> TCL
> Security Patch -> 2023-10-05

**Comment by R0rt1z2** [comment]
> Same issue about the TCL NxtPaper 11
> 
> > Model -> 9466X
> > Android Version -> 13
> > Product Manufracturer -> TCL
> > Security Patch -> 2023-10-05

The device is way too new to be supported by mtk-su.
