### ISSUE TITLE
This firmware cannot be supported

### ISSUE THREAD

**Issue by abewartech** [R0rt1z2/AutomatedRoot#15]
![image](https://github.com/R0rt1z2/AutomatedRoot/assets/29395602/f05a6faf-59b6-4ac9-813f-db17adf1a34c)

Not working superSu & magisk

**Comment by sen3064** [comment]
same for me

**Comment by R0rt1z2** [comment]
The device is not vulnerable to mtk-su then. There is nothing I can do about it.
