### ISSUE TITLE
Not working on Fire HD 10 (7.3.1.0)

### ISSUE THREAD

**Issue by daiceman2** [R0rt1z2/AutomatedRoot#2]
mtk-su should work on 7.3.1.0 versions of Fire HD 10 as per [its latest release](https://forum.xda-developers.com/hd8-hd10/orig-development/experimental-software-root-hd-8-hd-10-t3904595)

Recieve the following error when attempting to run the .bat in Windows:

```Detecting device information....
--------------------------------------
Device: KFMAWI
Brand: Amazon
ARCH: armeabi-v7a
Platform: mt8183
Android: 9
SELinux status: Permissive
Root: no
--------------------------------------
Detected armv7 arch.. Pushing armv7 mtk-su & files
arm/mtk-su: 1 file pushed, 0 skipped. 2.0 MB/s (64780 bytes in 0.031s)
arm/root.sh: 1 file pushed, 0 skipped. 1.1 MB/s (3055 bytes in 0.003s)
arm/su: 1 file pushed, 0 skipped. 8.9 MB/s (75356 bytes in 0.008s)
arm/supolicy: 1 file pushed, 0 skipped. 9.0 MB/s (42404 bytes in 0.005s)
arm/libsupol.so: 1 file pushed, 0 skipped. 24.5 MB/s (203236 bytes in 0.008s)
--------------------------------------
Pushed files succsefully!
--------------------------------------
SuperSU already installed... Skip the install
--------------------------------------
Starting Root Process...
This is an Amazon Device...
Checking FireOS version...
Your device seems to be in FireOS PS7310/940
/data/local/tmp/root.sh[30]: 7.0: unexpected '.'
cat: /fstab.mt8183*: No such file or directory
Warning: Reached EOF without any verify flag.
Warning: Attempt to cat fstab in vendor!
DM-Verity is present in this device. Abort!
--------------------------------------
PRESS ENTER TO CONTINUE.

**Comment by R0rt1z2** [comment]
> mtk-su should work on 7.3.1.0 versions of Fire HD 10 as per [its latest release](https://forum.xda-developers.com/hd8-hd10/orig-development/experimental-software-root-hd-8-hd-10-t3904595)
> 
> Recieve the following error when attempting to run the .bat in Windows:
> 
> ```
> --------------------------------------
> Device: KFMAWI
> Brand: Amazon
> ARCH: armeabi-v7a
> Platform: mt8183
> Android: 9
> SELinux status: Permissive
> Root: no
> --------------------------------------
> Detected armv7 arch.. Pushing armv7 mtk-su & files
> arm/mtk-su: 1 file pushed, 0 skipped. 2.0 MB/s (64780 bytes in 0.031s)
> arm/root.sh: 1 file pushed, 0 skipped. 1.1 MB/s (3055 bytes in 0.003s)
> arm/su: 1 file pushed, 0 skipped. 8.9 MB/s (75356 bytes in 0.008s)
> arm/supolicy: 1 file pushed, 0 skipped. 9.0 MB/s (42404 bytes in 0.005s)
> arm/libsupol.so: 1 file pushed, 0 skipped. 24.5 MB/s (203236 bytes in 0.008s)
> --------------------------------------
> Pushed files succsefully!
> --------------------------------------
> SuperSU already installed... Skip the install
> --------------------------------------
> Starting Root Process...
> This is an Amazon Device...
> Checking FireOS version...
> Your device seems to be in FireOS PS7310/940
> /data/local/tmp/root.sh[30]: 7.0: unexpected '.'
> cat: /fstab.mt8183*: No such file or directory
> Warning: Reached EOF without any verify flag.
> Warning: Attempt to cat fstab in vendor!
> DM-Verity is present in this device. Abort!
> --------------------------------------
> PRESS ENTER TO CONTINUE.
> ```

Hi,

The tool itself says why it's failing...

```DM-Verity is present in this device. Abort!```

Fire 7.3.1.0 has dm-verity which means that if you modify something in the /system partition, the tablet will refuse to boot.

Of course mtk-su works on 7.3.1.0 but you can only get bootless root.

Regards.

**Comment by daiceman2** [comment]
Ah, looks like I misunderstood how mtk-su works, thanks for clarifying!
