### ISSUE TITLE
[NOT WORKING]: Amazon Fire HD8 2017

### ISSUE THREAD

**Issue by bonelifer** [R0rt1z2/AutomatedRoot#3]
>    --------------------------------------------------
>    | DEVICE: KFDOWI                                 |
>    | BRAND: Amazon                                  |
>    | ARCH: arm64-v8a                                |
>    | PLATFORM: mt8163                               |
>    | ANDROID VERSION: 5.1.1                         |
>    | SELINUX STATUS: Enforcing                      |
>    | ROOT?: /system/bin/sh: which: not found        |
>    --------------------------------------------------
> [?] Checking platform...
> 
> [?] Check passed...
> 
> [?] Pushing files...
> 
> files/arm64/mtk-su: 1 file pushed. 6.0 MB/s (65136 bytes in 0.010s)
> files/common/root.sh: 1 file pushed. 2.1 MB/s (4436 bytes in 0.002s)
> files/arm64/su: 1 file pushed. 6.3 MB/s (108480 bytes in 0.016s)
> files/arm64/supolicy: 1 file pushed. 5.3 MB/s (42712 bytes in 0.008s)
> files/arm64/libsupol.so: 1 file pushed. 6.0 MB/s (334744 bytes in 0.053s)
> files/arm/mtk-su: 1 file pushed. 5.1 MB/s (64780 bytes in 0.012s)
> files/arm/su: 1 file pushed. 5.6 MB/s (75356 bytes in 0.013s)
> files/arm/supolicy: 1 file pushed. 4.9 MB/s (42404 bytes in 0.008s)
> files/arm/libsupol.so: 1 file pushed. 5.9 MB/s (203236 bytes in 0.033s)
> 
> [?] Installing SuperSU...
> 
> files/common/SuperSU.apk: 1 file pushed. 5.4 MB/s (6352735 bytes in 1.115s)
> 	pkg: /data/local/tmp/SuperSU.apk
> Success
> [?] Starting Root Process...
> 
> Failed critical init step 4
> This platform cannot be supported
> [?] Press any key to continue...

**Comment by R0rt1z2** [comment]
> > ## | DEVICE: KFDOWI                                 |
> > | BRAND: Amazon                                  |
> > | ARCH: arm64-v8a                                |
> > | PLATFORM: mt8163                               |
> > | ANDROID VERSION: 5.1.1                         |
> > | SELINUX STATUS: Enforcing                      |
> > | ROOT?: /system/bin/sh: which: not found        |
> > [?] Checking platform...
> > [?] Check passed...
> > [?] Pushing files...
> > files/arm64/mtk-su: 1 file pushed. 6.0 MB/s (65136 bytes in 0.010s)
> > files/common/root.sh: 1 file pushed. 2.1 MB/s (4436 bytes in 0.002s)
> > files/arm64/su: 1 file pushed. 6.3 MB/s (108480 bytes in 0.016s)
> > files/arm64/supolicy: 1 file pushed. 5.3 MB/s (42712 bytes in 0.008s)
> > files/arm64/libsupol.so: 1 file pushed. 6.0 MB/s (334744 bytes in 0.053s)
> > files/arm/mtk-su: 1 file pushed. 5.1 MB/s (64780 bytes in 0.012s)
> > files/arm/su: 1 file pushed. 5.6 MB/s (75356 bytes in 0.013s)
> > files/arm/supolicy: 1 file pushed. 4.9 MB/s (42404 bytes in 0.008s)
> > files/arm/libsupol.so: 1 file pushed. 5.9 MB/s (203236 bytes in 0.033s)
> > [?] Installing SuperSU...
> > files/common/SuperSU.apk: 1 file pushed. 5.4 MB/s (6352735 bytes in 1.115s)
> > pkg: /data/local/tmp/SuperSU.apk
> > Success
> > [?] Starting Root Process...
> > Failed critical init step 4
> > This platform cannot be supported
> > [?] Press any key to continue...

Hi,

```Failed critical init step 4```
Means your device is not vulnerable to mtk-su probably because FireOS version is updated to the latest version.

Regards.
