### ISSUE TITLE
Doesn't work on Alcatel 3X 5048Y

### ISSUE THREAD

**Issue by Klairm** [R0rt1z2/AutomatedRoot#5]
* **Issue name**: The tool fails when executing the mtk-su binary
* **Device**: Alcatel 3X 5048Y
* **OS of the computer**: Linux.
* **Tool version**: Latest one (v.5.2)
* **Error log**:
    ```
  Getting device information...

    DEVICE: 5048Y_EEA                              
    BRAND: TCL                                     
    ARCH: arm64-v8a                              
    PLATFORM: mt6763                              
    ANDROID VERSION: 9                           
    SELINUX STATUS: Enforcing                   
    ROOT?

 Checking platform...

 Check passed...

 Pushing files...

 SuperSU it's already installed...

 Starting Root Process...

Failed critical init step 1 ```

**Comment by R0rt1z2** [comment]
Hey @Klairm,
`Failed critical init step 1` means your device isn't supported by mtk-su (I'm guessing Alcatel already patched the cmdq vuln at kernel-level) so I can't really help you here 😅
If the phone had earlier FW versions try downgrading.
Regards.

**Comment by Klairm** [comment]
Yes the problem is Alcatel doesn't provide the ROMs for my device  , anyways thanks!
