### ISSUE TITLE
Frozen on FireTV 2 v5.2.8.0 during Bootless Root

### ISSUE THREAD

**Issue by aaroncelestin** [R0rt1z2/AutomatedRoot#9]
![mtk-su-capture](https://user-images.githubusercontent.com/51392307/140620494-777305f1-e6b7-443d-8059-aec6d042dc65.JPG)
 It's stuck on init.d scripts support after ad showed.

Is it just that my device/ firmware is not supported?

**Comment by R0rt1z2** [comment]
> ![mtk-su-capture](https://user-images.githubusercontent.com/51392307/140620494-777305f1-e6b7-443d-8059-aec6d042dc65.JPG) It's stuck on init.d scripts support after ad showed.
> 
> Is it just that my device/ firmware is not supported?

Hi,

EDIT: Forgot to read the title.. Can you try with the normal root method?

Regards.
